collections:
  - name: azure.azcollection
    version: 3.9.0 # https://github.com/ansible-collections/azure/releases
  - name: community.crypto
    version: 3.0.4 # https://github.com/ansible-collections/community.crypto/releases