- name: Enable MicroK8s RBAC addon
  hosts: all
  gather_facts: false
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Check whether RBAC is already enabled
      ansible.builtin.command: microk8s status --addon rbac --format short
      register: rbac_status
      changed_when: false

    - name: Enable MicroK8s rbac addon
      ansible.builtin.command: microk8s enable rbac
      when: "'enabled' not in rbac_status.stdout"

    - name: Wait for MicroK8s API to become ready
      ansible.builtin.command: microk8s status --wait-ready --timeout 600
      changed_when: false
      when: "'enabled' not in rbac_status.stdout"
