- name: Revert Secure Private Server Changes
  hosts: all
  gather_facts: false
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_password: "{{ user_password }}"
        
  tasks:
    - name: Restore SSH port to initial value
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?Port"
        line: "Port {{ initial_port }}"
      
    - name: Enable SSH root login
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin yes"
      
    - name: Enable password authentication
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication yes"
      
    - name: Reset root password to initial value
      ansible.builtin.user:
        name: root
        state: present
        password: "{{ initial_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      
    - name: Reset user password to initial value
      ansible.builtin.user:
        name: "{{ initial_username }}"
        state: present
        password: "{{ initial_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"

    - name: Restart SSH service
      ansible.builtin.systemd_service:
        name: ssh
        state: restarted
        enabled: true
      vars:
        ansible_become_password: "{{ initial_password }}"