#!/bin/bash

set -euo pipefail

source .venv/bin/activate

# Per-apply ssh-agent. The cluster SSH key is generated by Terraform and piped
# directly into this agent (see modules/provision_hetzner_server), so the key
# never lands on disk. Killed on exit so nothing is left behind.
eval "$(ssh-agent -s)" >/dev/null
trap 'ssh-agent -k >/dev/null 2>&1 || true' EXIT

terraform plan -out=tfplan
terraform apply -auto-approve tfplan
