#!/bin/bash

set -euo pipefail

source .venv/bin/activate

# Per-apply ssh-agent. The cluster SSH key is generated by Terraform and piped
# directly into this agent (see modules/provision_hetzner_server), so the key
# never lands on disk. Killed on exit so nothing is left behind.
eval "$(ssh-agent -s)" >/dev/null
trap 'ssh-agent -k >/dev/null 2>&1 || true' EXIT

# Pre-load the SSH private key from Key Vault into ssh-agent. This is what
# prevents terraform_data.ssh_agent_loaded from churning on every fresh shell:
# without this, each new agent socket is empty and the resource has to re-run
# its local-exec to install the key. With this, the agent already has the key
# by the time Terraform plans, so triggers_replace can stay stable.
#
# Best-effort: tolerated failures —
#   - First apply: the secret does not exist in Key Vault yet (it is created
#     by secrets.tf at the end of the apply). Terraform's ssh_agent_loaded
#     bootstraps the agent in that one case.
#   - No az / not logged in / no Key Vault access: also falls through to the
#     bootstrap path. If the key is also not yet in state, Ansible later
#     errors with a clear authentication failure.
vault_name="${AZURE_KEYVAULT_NAME:-}"
if [ -z "$vault_name" ] && [ -f backend.tf ]; then
  vault_name=$(sed -n '/variable "environment_name"/,/^}/ s/.*default[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' backend.tf)
fi

if [ -n "$vault_name" ] && command -v az >/dev/null 2>&1; then
  if ssh_key=$(az keyvault secret show \
        --vault-name "$vault_name" \
        --name ssh-private-key \
        --query value -o tsv 2>/dev/null) && [ -n "$ssh_key" ]; then
    printf '%s\n' "$ssh_key" | ssh-add - >/dev/null 2>&1 \
      && echo "Loaded SSH key from Key Vault $vault_name into ssh-agent"
  fi
fi

# Preflight: if a server already exists in state, this apply will reach it over
# SSH and the K8s API — both Twingate-only now. Fail fast with a clear message
# if the operator's Twingate client is not connected. Skipped silently on the
# very first apply (no state/outputs yet).
if pre_host=$(terraform output -raw hcloud_ipv4_address 2>/dev/null) \
  && pre_port=$(terraform output -raw hcloud_ssh_port 2>/dev/null) \
  && [ -n "$pre_host" ] && [ -n "$pre_port" ] \
  && command -v nc >/dev/null 2>&1; then
  if ! nc -z -w 5 "$pre_host" "$pre_port" 2>/dev/null; then
    echo "Existing server $pre_host:$pre_port is unreachable on SSH." >&2
    echo "Connect your Twingate client before applying (SSH and the K8s API are Twingate-only)." >&2
    echo "Break-glass: Hetzner Cloud Console — add a temporary inbound rule; terraform reverts it on the next apply." >&2
    exit 1
  fi
fi

# Forward extra args to plan so callers can do e.g.
#   scripts/create.sh -replace='module.provision_hetzner_server.hcloud_server.this'
terraform plan -out=tfplan "$@"
terraform apply -auto-approve tfplan
