- name: Secure Private Server
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Enable SSH key authentication for user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key }}"
    - name: Change password for existing user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
        password: "{{ password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
